GET http://localhost:81/api/kuna/me

###

GET http://localhost:81/api/kuna/getbalance

###

GET http://localhost:81/api/kuna/getmarkets

###

GET http://localhost:81/api/kuna/getactiveorders?market=bchuah


###

POST http://localhost:81/api/kuna/cancelorders
Content-Type: application/json

{
    "orderids": "1943095193"
}


###

GET http://localhost:81/api/kuna/kunacode?code=37pBc-ibnFk-vWCi4-4QmZa-Hkjv9-t4NuN-Q6DW3-qzLf8-yGiad-UAH-KCode

###

POST http://localhost:81/api/kuna/kunacodeactivate
Content-Type: application/json

{
    "code": "37pBc-ibnFk-vWCi4-4QmZa-Hkjv9-t4NuN-Q6DW3-qzLf8-yGiad-UAH-KCode"
}

###

GET http://localhost:81/api/kuna/getactiveorders?market=bchuah
