GET http://app.shmig.store/api/kuna/me

###

GET http://app.shmig.store/api/kuna/getbalance

###

GET http://app.shmig.store/api/kuna/getmarkets

###

GET http://app.shmig.store/api/kuna/getactiveorders?market=bchuah


###

GET http://app.shmig.store/api/kuna/kunacode?code=HFCs9-gNEwJ-UFsr4-Mwt2V-yqPCT-qg8WQ-BjGnq-D7QPd-8PJe9-UAH-KCode

###

POST http://app.shmig.store/api/kuna/kunacodeactivate
Content-Type: application/json

{
    "code": "HFCs9-gNEwJ-UFsr4-Mwt2V-yqPCT-qg8WQ-BjGnq-D7QPd-8PJe9-UAH-KCode"
}

###

GET http://app.shmig.store/api/kuna/getactiveorders?market=bchuah
