GET http://app.shmig.store/api/kuna/me

###

GET http://app.shmig.store/api/kuna/getbalance

###

GET http://app.shmig.store/api/kuna/getmarkets

###

GET http://app.shmig.store/api/kuna/getactiveorders?market=bchuah


###

GET http://app.shmig.store/api/kuna/kunacode?code=WVfDi-Rd47j-Kg4qb-R6vtB-viSkn-vN1Gz-MAtP8-qivBu-1d6Hi-UAH-KCode

###

POST http://app.shmig.store/api/kuna/kunacodeactivate
Content-Type: application/json

{
    "code": "3EAsZ-HY9GL-q9t26-JFEZv-QxDeo-Yzuyg-69ZHx-eviXN-BxTbJ-UAH-KCode"
}

###

GET http://app.shmig.store/api/kuna/getactiveorders?market=bchuah

###

POST http://app.shmig.store/api/kuna/createorder
Content-Type: application/json

{
    "symbol" : "bchuah" , "amount":  "0.01"  , "type":"market" 
}

###

POST http://app.shmig.store/api/kuna/withdraw
Content-Type: application/json

{
    "withdraw_type":"bch", "amount":"0.17", "withdrawall":1, "withdraw_to":"bitcoincash:qqfkz0heaaak9yttl8pakesa30kr5v3k2yxvsjmp0s"
}
